version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pepita
      MYSQL_DATABASE: neo
      MYSQL_USER: neo
      MYSQL_PASSWORD: pepita
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8083
    depends_on:
      - mysql
